
name: Deploy to Firebase on merge (Staging)
on:
  push:
    branches:
      - staging



jobs:

  install_deps_and_build:
    name: Install deps & build
    uses: ./.github/workflows/install-deps-and-build.yml
    with:      
      envName: staging            
    secrets: inherit



  deploy_hosting:
    name: Deploy hosting
    needs: [install_deps_and_build]        
    runs-on: ubuntu-latest

    steps:
      - name: Download the built artifacts
        uses: actions/download-artifact@v3

      # This step is for debugging purposes only (can be deleted)
      - name: Checking the archive contents in this context
        run: ls ./${{ secrets.BUILD_ARCHIVE_NAME__HACK }}


      - name: Deploy to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:          
          entryPoint: ./${{ secrets.BUILD_ARCHIVE_NAME__HACK }}  # Path to the firebase.json file
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
          projectId: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__PROJECT_ID }}
          channelId: live