
name: Deploy to Firebase on PR (Staging)
on: 
  pull_request:
    branches:
      - staging

# Create environment variables applicable to all jobs in this file Note: We can also declare them at the individual job or step level.
env: 
  BUILD_ARCHIVE_NAME: build-archive



jobs:
  install_deps_and_build:
    name: Install deps & build
    uses: ./.github/workflows/install-deps-and-build.yml
    with:
      # Note: I intentionally avoided naming this input "environement" since GitHub has a field called that
      #        (but you have to set up more stuff on GitHub to use that and it is not available for private repos I think)
      # envName: staging
      envName: Bob
      # build_archive_name: ${{ env.BUILD_ARCHIVE_NAME }}
    secrets: inherit


  deploy_hosting_preview:
    name: Deploy hosting preview
    needs: [install_deps_and_build]
    
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - name: Download the built artifact
        uses: actions/download-artifact@v3
        # with:       
          # The archive name to download. If you omit the 'name' input, then all artifacts of this workflow run are downloaded
          #name: ${{ env.BUILD_ARCHIVE_NAME }}


      # This step is for debugging purposes only (can be deleted)
      - name: Checking the archive contents in this context
        run: ls ${{ env.BUILD_ARCHIVE_NAME }}


      - name: Deploy to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./${{ env.BUILD_ARCHIVE_NAME }}  # Path to the firebase.json file
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
          projectId: niceness-game--staging




  # build_and_preview_hosting:
  #   if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout the repository first, otherwise the workflow won't be able to find local actions
  #     # - name: Checkout the commit
  #     #   uses: actions/checkout@v2

  #     #- name: Install deps, then build
  #       # Note: Environment variables defined above the 'jobs' (in this file) are accessible in the called action
  #       #uses: ./.github/actions/install-deps-and-build
  #       # with:
  #       #   environment: staging

  #     - name: Deploy to Firebase hosting
  #       uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
  #         projectId: niceness-game--staging



