
name: Deploy to Firebase on PR (Staging)
on: 
  pull_request:
    branches:
      - staging

# Create environment variables for the build that happens on GitHub. Vars attach to process.env.
#  Note: When declaring these up here (above 'jobs'), they become accessible to all jobs in this file (could be useful or could be a security concern)
#        We can also declare them a the individual job or step level.
# env: 
#   NEXT_PUBLIC__FIREBASE_CONFIG__API_KEY: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__API_KEY }}
#   NEXT_PUBLIC__FIREBASE_CONFIG__AUTH_DOMAIN: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__AUTH_DOMAIN }}
#   NEXT_PUBLIC__FIREBASE_CONFIG__PROJECT_ID: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__PROJECT_ID }}
#   NEXT_PUBLIC__FIREBASE_CONFIG__STORAGE_BUCKET: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__STORAGE_BUCKET }}
#   NEXT_PUBLIC__FIREBASE_CONFIG__MESSAGING_SENDER_ID: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__MESSAGING_SENDER_ID }}
#   NEXT_PUBLIC__FIREBASE_CONFIG__APP_ID: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__APP_ID }}
#   NEXT_PUBLIC__FIREBASE_CONFIG__MEASUREMENT_ID: ${{ secrets.STAGING__NEXT_PUBLIC__FIREBASE_CONFIG__MEASUREMENT_ID }}


jobs:
  install_deps_and_build:
    uses: ./.github/workflows/install-deps-and-build.yml
    with:
      # Note: I intentionally avoided naming this input "environement" since GitHub has a field called that
      #        (but you have to set up more stuff on GitHub to use that and it is not available for private repos I think)
      envName: staging
    secrets: inherit


  deploy_hosting_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - name: (temp) Checking if the build exists
        run: ls ./out

      # - name: Deploy to Firebase hosting
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
      #     projectId: niceness-game--staging




  # build_and_preview_hosting:
  #   if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout the repository first, otherwise the workflow won't be able to find local actions
  #     # - name: Checkout the commit
  #     #   uses: actions/checkout@v2

  #     #- name: Install deps, then build
  #       # Note: Environment variables defined above the 'jobs' (in this file) are accessible in the called action
  #       #uses: ./.github/actions/install-deps-and-build
  #       # with:
  #       #   environment: staging

  #     - name: Deploy to Firebase hosting
  #       uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
  #         projectId: niceness-game--staging



