
name: Deploy to Firebase on merge (Staging)
on:
  push:
    branches:
      - staging

env: 
  # NOTE: Unfortunately we cannot use this as the value of an input ("with:") to a reusable workflow.
  #        So if we change this value, be sure to also change occurances of this *value* (not the key) elsewhere in the file.
  BUILD_ARCHIVE_NAME: build-archive


jobs:

  install_deps_and_build:
    name: Install deps & build
    uses: ./.github/workflows/install-deps-and-build.yml
    with:      
      envName: staging      
      build_archive_name: build-archive # <-- Will need to update that if updating the environment variable above (see notes above)
    secrets: inherit



  deploy_hosting:
    name: Deploy hosting
    needs: [install_deps_and_build]        
    runs-on: ubuntu-latest

    steps:
      - name: Download the built artifacts
        uses: actions/download-artifact@v3

      # This step is for debugging purposes only (can be deleted)
      - name: Checking the archive contents in this context
        run: ls ./$BUILD_ARCHIVE_NAME # <-- Works as expected


      - name: Deploy to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:          
          entryPoint: ./${{ env.BUILD_ARCHIVE_NAME }}  # Path to the firebase.json file
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
          projectId: niceness-game--staging
          channelId: live