
name: Deploy to Firebase on PR (Staging)
on: 
  pull_request:
    branches:
      - staging

# Create environment variables applicable to all jobs in this file 
#  Notes: (1) We can also declare them at the individual job or step level.
#         (2) How to access these env variables: '$VAR_NAME' or '${{ env.VAR_NAME }}', depending on the context. The GitHub docs show both approaches but are not clear on when to use which.
env: 
  BUILD_ARCHIVE_NAME: build-archive



jobs:
  install_deps_and_build:
    name: Install deps & build
    uses: ./.github/workflows/install-deps-and-build.yml
    with:
      # Note: I intentionally avoided naming this input "environement" since GitHub has a field called that
      #        (but you have to set up more stuff on GitHub to use that and it is not available for private repos I think)
      envName: staging      
      # build_archive_name: $BUILD_ARCHIVE_NAME
      # build_archive_name: ${{ env.BUILD_ARCHIVE_NAME }}
      build_archive_name: ${{ echo env.BUILD_ARCHIVE_NAME }}
    secrets: inherit


  deploy_hosting_preview:
    name: Deploy hosting preview
    needs: [install_deps_and_build]
    
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - name: Download the built artifact
        uses: actions/download-artifact@v3
        # with:       
          # The archive name to download. If you omit the 'name' input, then all artifacts of this workflow run are downloaded
          #name: $BUILD_ARCHIVE_NAME


      # This step is for debugging purposes only (can be deleted)
      - name: Checking the archive contents in this context
        run: ls ./$BUILD_ARCHIVE_NAME


      - name: Deploy to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./$BUILD_ARCHIVE_NAME  # Path to the firebase.json file
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICENESS_GAME__STAGING }}'
          projectId: niceness-game--staging

